config/routes.rb
Rails.application.routes.draw do
  root to: 'students#index'

  resources :students do
    resources :class_schedules do
      member do
        post    'enroll'
        delete  'drop'
      end
    end
  end

  resources :subjects, :professors, :students do
  	resources :class_schedules do
      resources :reviews
    end
  end

  resources :subjects, :professors do
    resources :reviews
  end

  resources :subjects do
  	resources :professors
  end

  resources :professors do
  	resources :subjects
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
	has_and_belongs_to_many	:class_schedules, join_table: :class_schedules_students
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
    end
  end

  private
  
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:name)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table cellpadding="25">
    <tr>
      <td>Name:</td>
      <td><%= form.text_field :name %></td>
    </tr>
  </table>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table cellpadding="25">
  <thead>
    <tr>
      <th>Name</th>
      <th>Classes</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% if @students.empty? %>
      <tr>
        <td align="center" colspan="3">No Students Available.</td>
      </tr>
    <% else %>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.name %></td>
          <td align="center"><%= link_to pluralize(student.class_schedules.size, 'Class'), student_class_schedules_path(student) %></td>
          <td align="center">
            <%= link_to student, title: 'Show' do %>
              <%= fa_icon 'eye' %>
            <% end %> &nbsp;
            <%= link_to edit_student_path(student), title: 'Edit' do %>
              <%= fa_icon 'edit' %>
            <% end %> &nbsp;
            <%= link_to student, method: :delete, data: { confirm: 'Are you sure?' }, title: 'Destroy' do %>
              <%= fa_icon 'trash' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_student_path do %>
  <%= fa_icon 'plus' %> New Student
<% end %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Student Details</h1>

<table cellpadding="25">
	<tr>
		<td align="right">Name:</td>
		<td><%= @student.name %></td>
	</tr>

	<tr>
		<td align="right">Classes:</td>
		<td><%= link_to "View #{pluralize(@student.class_schedules.size, 'Class')}", polymorphic_path([@student, ClassSchedule]) %></td>
	</tr>
</table>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>