config/routes.rb
Rails.application.routes.draw do
  root to: 'students#index'

  resources :students do
    resources :class_schedules do
      member do
        post    'enroll'
        delete  'drop'
      end
    end
  end

  resources :subjects, :professors, :students do
  	resources :class_schedules do
      resources :reviews
    end
  end

  resources :subjects, :professors do
    resources :reviews
  end

  resources :subjects do
  	resources :professors
  end

  resources :professors do
  	resources :subjects
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/class_schedule.rb
class ClassSchedule < ApplicationRecord
	has_and_belongs_to_many	:students, join_table: :class_schedules_students

	has_many :reviews, as: :reviewable

	belongs_to :professor
	belongs_to :subject

	delegate :name, to: :professor, prefix: true

	validates_presence_of :days, :time_schedule, :room

	validate :daysss

	def display_days
		dd = []

		days.split('').each { |i| dd << AppHelper.days_index[i.to_sym] }

		dd.join(' | ')
	end

	def ratings
		reviews.empty? ? nil : reviews.average(:rating).round
	end

	def days_index
		@days_index
	end

	def days_index=(val)
		@days_index = val
	end

	private

		def daysss
			logger.debug("=" * 1000)
			logger.debug("---#{@days_index}")
			logger.debug("---#{days_index}")
		end
end

app/controllers/class_schedules_controller.rb
class ClassSchedulesController < ApplicationController
  before_action :set_class_schedule, only: [:show, :edit, :update, :destroy, :enroll, :drop]
  before_action :set_parent

  def index
    @class_schedules = ClassSchedule.all
    @class_schedules = Professor.find(params[:professor_id]).class_schedules if params[:professor_id]
    @class_schedules = Subject.find(params[:subject_id]).class_schedules if params[:subject_id]
    @class_schedules.includes!([:reviews, :professor, :subject])
  end

  def show
  end

  def new
    @class_schedule = ClassSchedule.new
  end

  def edit
  end

  def create
    @class_schedule = ClassSchedule.new(class_schedule_params)
    # @class_schedule.days = params[:days_index].present? ? params[:days_index].join() : ''
    @class_schedule.professor = Professor.find(params[:professor_id])
    @class_schedule.subject = Subject.find(params[:subject_id])

    respond_to do |format|
      if @class_schedule.save
        format.html { redirect_to polymorphic_path([@parent, @class_schedule]), notice: 'Class schedule was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      # @class_schedule.days = params[:days_index].present? ? params[:days_index].join() : ''
      @class_schedule.professor = Professor.find(params[:professor_id])
      @class_schedule.subject = Subject.find(params[:subject_id])

      if @class_schedule.update(class_schedule_params)
        format.html { redirect_to polymorphic_path([@parent, @class_schedule]), notice: 'Class schedule was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @class_schedule.destroy
    respond_to do |format|
      format.html { redirect_to polymorphic_path([@parent, ClassSchedule]), notice: 'Class schedule was successfully destroyed.' }
    end
  end

  def enroll
    @parent.class_schedules << @class_schedule
    @parent.save

    respond_to do |format|
      format.html { redirect_to polymorphic_path([@parent, ClassSchedule]), notice: 'Student was successfully enrolled to class' }
    end
  end

  def drop
    @parent.class_schedules.delete(@class_schedule)
    @parent.save

    respond_to do |format|
      format.html { redirect_to polymorphic_path([@parent, ClassSchedule]), notice: 'Student was successfully dropped out of class' }
    end
  end

  private

    def set_class_schedule
      @class_schedule = ClassSchedule.find(params[:id])
    end

    def set_parent
      @parent = Professor.find(params[:professor_id]) if params[:professor_id]
      @parent = Subject.find(params[:subject_id]) if params[:subject_id]
      @parent = Student.find(params[:student_id]) if params[:student_id]
    end
    
    def class_schedule_params
      params.require(:class_schedule).permit(:time_schedule, :days, :room, :days_index)
    end
end

app/helpers/class_schedules_helper.rb
module ClassSchedulesHelper
end

app/views/class_schedules/_form.html.erb
<%= form_with(model: [parent, class_schedule], url: polymorphic_path([parent, class_schedule]), local: true) do |form| %>
  <% if class_schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(class_schedule.errors.count, "error") %> prohibited this class_schedule from being saved:</h2>

      <ul>
      <% class_schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table cellpadding="25">
    <% unless params[:subject_id] %>
      <tr>
        <td>Subject:</td>
        <td><%= select_tag 'subject_id', options_from_collection_for_select(Subject.all, "id", "display_subject", class_schedule.new_record? ? nil : class_schedule.subject.id), prompt: "Select Subject..." %></td>
      </tr>
    <% end %>

    <% unless params[:professor_id] %>
      <tr>
        <td>Professor:</td>
        <td><%= select_tag 'professor_id', options_from_collection_for_select(Professor.all, "id", "name", class_schedule.new_record? ? nil : class_schedule.professor.id), prompt: "Select Instructor..." %></td>
      </tr>
    <% end %>

    <tr>
      <td>Time:</td>
      <td><%= form.text_field :time_schedule %></td>
    </tr>

    <tr>
      <td>Days:</td>
      <td>
        <% AppHelper.days_index.each do |k, v| %>
          <%= check_box_tag('class_schedule[days_index][]', k, class_schedule.new_record? ? false : class_schedule.days.include?(k.to_s)) %> <%= v %> <br>
        <% end %>
      </td>
    </tr>

    <tr>
      <td>Room:</td>
      <td><%= form.text_field :room %></td>
    </tr>
  </table>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/class_schedules/edit.html.erb
<h1>Editing Class Schedule</h1>

<%= render 'form', class_schedule: @class_schedule, parent: @parent %>

<%= link_to 'Show', polymorphic_path([@parent, @class_schedule]) %> |
<%= link_to 'Back', polymorphic_path([@parent, ClassSchedule]) %>

app/views/class_schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Class Schedules</h1>

<table cellpadding="25">
  <thead>
    <tr>
      <% unless params[:subject_id] %>
        <th>Subject</th>
      <% end %>

      <% unless params[:professor_id] %>
        <th>Instructor</th>
      <% end %>

      <th>Days</th>
      <th>Time</th>
      <th>Room</th>

      <th>Ratings</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% if @class_schedules.empty? %>
      <tr>
        <td align="center" colspan="7">No Class Schedules Available.</td>
      </tr>
    <% else %>
      <% @class_schedules.each do |class_schedule| %>
        <tr>
          <% unless params[:subject_id] %>
            <td><%= link_to class_schedule.subject.display_subject, subject_path(class_schedule.subject) %></td>
          <% end %>

          <% unless params[:professor_id] %>
            <td><%= link_to class_schedule.professor_name, professor_path(class_schedule.professor) %></td>
          <% end %>
          
          <td align="center"><%= class_schedule.display_days %></td>
          <td align="center"><%= class_schedule.time_schedule %></td>
          <td align="center"><%= class_schedule.room %></td>
          <td align="center"><%= starred_rating(class_schedule.ratings) %></td>

          <td align="center">
            <% if params[:student_id] %>
              <% if @parent.class_schedules.include?(class_schedule) %>
                <%= link_to polymorphic_path([@parent, class_schedule], action: :drop), title: 'Drop out of this class', method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <%= fa_icon 'unlink' %>
                <% end %>
              <% else %>
                <%= link_to polymorphic_path([@parent, class_schedule], action: :enroll), title: 'Enroll to this class', method: :post, data: { confirm: 'Are you sure?' } do %>
                  <%= fa_icon 'plus-square' %>
                <% end %>
              <% end %>
              &nbsp;
            <% end %>
            <%= link_to polymorphic_path([@parent, class_schedule]), title: 'Show' do %>
              <%= fa_icon 'eye' %>
            <% end %> &nbsp;
            <% unless params[:student_id] %>
              <%= link_to edit_polymorphic_path([@parent, class_schedule]), title: 'Edit' do %>
                <%= fa_icon 'edit' %>
              <% end %> &nbsp;
              <%= link_to polymorphic_path([@parent, class_schedule]), method: :delete, data: { confirm: 'Are you sure?' }, title: 'Delete' do %>
                <%= fa_icon 'trash' %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<% unless params[:student_id] %>
  <%= link_to new_polymorphic_path([@parent, ClassSchedule]) do %>
    <%= fa_icon 'plus' %> New Class Schedule
  <% end %>
<% end %>

app/views/class_schedules/new.html.erb
<h1>New Class Schedule</h1>

<%= render 'form', class_schedule: @class_schedule, parent: @parent %>

<%= link_to 'Back', polymorphic_path([@parent, ClassSchedule]) %>

app/views/class_schedules/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Class Details</h1>

<h1><%= starred_rating(@class_schedule.ratings, '2x') %></h1>

<table cellpadding="25">
	<tr>
		<td align="right">Professor:</td>
		<td>
			<%= link_to @class_schedule.professor_name, professor_path(@class_schedule.professor) %>
		</td>
		<td>
			<%= starred_rating(@class_schedule.professor.ratings) %>
		</td>
	</tr>

	<tr>
		<td align="right">Subject:</td>
		<td><%= link_to @class_schedule.subject.display_subject, subject_path(@class_schedule.subject) %></td>
		<td>
			<%= starred_rating(@class_schedule.subject.ratings) %>
		</td>
	</tr>

	<tr>
		<td align="right">Schedule:</td>
		<td><%= @class_schedule.display_days %> <br> <%= @class_schedule.time_schedule %></td>
	</tr>

	<tr>
		<td align="right">Room:</td>
		<td><%= @class_schedule.room %></td>
	</tr>

	<tr>
		<td align="right">Reviews:</td>
		<td><%= link_to "View #{pluralize(@class_schedule.reviews.size, 'Review')}", polymorphic_path([@parent, @class_schedule, Review]) %></td>
	</tr>
</table>

<% if params[:student_id] %>
	<% if @parent.class_schedules.include?(@class_schedule) %>
		<%= link_to polymorphic_path([@parent, @class_schedule], action: :drop), method: :delete, data: { confirm: 'Are you sure?' } do %>
			<%= fa_icon 'unlink 2x' %> Drop out of this class
		<% end %>
	<% else %>
		<%= link_to polymorphic_path([@parent, @class_schedule], action: :enroll), method: :post, data: { confirm: 'Are you sure?' } do %>
			<%= fa_icon 'plus-square 2x' %> Enroll to this class
		<% end %>
	<% end %>
<% end %>

<%= link_to 'Edit', edit_polymorphic_path([@parent, @class_schedule]) unless params[:student_id] %> |
<%= link_to 'Back', polymorphic_path([@parent, ClassSchedule]) %>