config/routes.rb
Rails.application.routes.draw do
  root to: 'students#index'

  resources :students do
    resources :class_schedules do
      member do
        post    'enroll'
        delete  'drop'
      end
    end
  end

  resources :subjects, :professors, :students do
  	resources :class_schedules do
      resources :reviews
    end
  end

  resources :subjects, :professors do
    resources :reviews
  end

  resources :subjects do
  	resources :professors
  end

  resources :professors do
  	resources :subjects
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/professor.rb
class Professor < ApplicationRecord
	has_many :class_schedules
	has_many :subjects, through: :class_schedules
	has_many :reviews, as: :reviewable

	def ratings
		reviews.empty? ? nil : reviews.average(:rating).round
	end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]

  def index
    @professors = Professor.all
    @professors = Subject.find(params[:subject_id]).professors.distinct if params[:subject_id]
    @professors = @professors.includes(:reviews)
  end

  def show
    @professor = Professor.find(params[:id])
  end

  def new
    @professor = Professor.new
  end

  def edit
  end

  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url, notice: 'Professor was successfully destroyed.' }
    end
  end

  private

    def set_professor
      @professor = Professor.find(params[:id])
    end

    def professor_params
      params.require(:professor).permit(:name)
    end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_form.html.erb
<%= form_with(model: professor, local: true) do |form| %>
  <% if professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
      <% professor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table cellpadding="25">
    <tr>
      <td>Name:</td>
      <td><%= form.text_field :name %></td>
    </tr>
  </table>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/professors/edit.html.erb
<h1>Editing Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Show', @professor %> |
<%= link_to 'Back', professors_path %>

app/views/professors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professors</h1>

<table cellpadding="25">
  <thead>
    <tr>
      <th>Name</th>
      <th>Ratings</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% if @professors.empty? %>
      <tr>
        <td align="center" colspan="3">No Professors Available.</td>
      </tr>
    <% else %>
      <% @professors.each do |professor| %>
        <tr>
          <td><%= professor.name %></td>
          <td align="center"><%= starred_rating(professor.ratings) %></td>
          <td align="center">
            <%= link_to professor, title: 'Show' do %>
              <%= fa_icon 'eye' %>
            <% end %> &nbsp;
            <%= link_to edit_professor_path(professor), title: 'Edit' do %>
              <%= fa_icon 'edit' %>
            <% end %> &nbsp;
            <%= link_to professor, method: :delete, data: { confirm: 'Are you sure?' }, title: 'Delete' do %>
              <%= fa_icon 'trash' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<% unless params[:subject_id] %>
  <%= link_to new_professor_path do %>
    <%= fa_icon 'plus' %> New Professor
  <% end %>
<% end %>

app/views/professors/new.html.erb
<h1>New Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Back', professors_path %>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Professor Details<h1>

<h1><%= starred_rating(@professor.ratings, '2x') %></h1>

<table cellpadding="25">
	<tr>
		<td align="right">Name:</td>
		<td><%= @professor.name %></td>
	</tr>

	<tr>
		<td align="right">Classes:</td>
		<td><%= link_to "View #{pluralize(@professor.class_schedules.size, 'Class')}", polymorphic_path([@professor, ClassSchedule]) %></td>
	</tr>

	<tr>
		<td align="right">Subjects:</td>
		<td><%= link_to "View #{pluralize(@professor.subjects.distinct.size, 'Subject')}", polymorphic_path([@professor, Subject]) %></td>
	</tr>

	<tr>
		<td align="right">Reviews:</td>
		<td>
			<%= link_to "View #{pluralize(@professor.reviews.size, 'Review')}", polymorphic_path([@professor, Review]) %>
		</td>
	</tr>
</table>

<%= link_to 'Edit', edit_professor_path(@professor) %> |
<%= link_to 'Back', professors_path %>