config/routes.rb
Rails.application.routes.draw do
  root to: 'students#index'

  resources :students do
    resources :class_schedules do
      member do
        post    'enroll'
        delete  'drop'
      end
    end
  end

  resources :subjects, :professors, :students do
  	resources :class_schedules do
      resources :reviews
    end
  end

  resources :subjects, :professors do
    resources :reviews
  end

  resources :subjects do
  	resources :professors
  end

  resources :professors do
  	resources :subjects
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
	has_many	:class_schedules
	has_many	:professors, through: :class_schedules
	has_many	:reviews, as: :reviewable

	def display_subject
		"#{self.code}: #{self.name}"
	end
	
	def ratings
		reviews.empty? ? nil : reviews.average(:rating).round
	end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  def index
    @subjects = Subject.all
    @subjects = Professor.find(params[:professor_id]).subjects.distinct if params[:professor_id]
    @subjects = @subjects.includes(:reviews)
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new
  end

  def edit
  end

  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
    end
  end

  private

    def set_subject
      @subject = Subject.find(params[:id])
    end

    def subject_params
      params.require(:subject).permit(:code, :name)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table cellpadding="25">
    <tr>
      <td>Subject Code:</td>
      <td><%= form.text_field :code %></td>
    </tr>

    <tr>
      <td>Subject Name:</td>
      <td><%= form.text_field :name %></td>
    </tr>
  </table>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table cellpadding="25">
  <thead>
    <tr>
      <th>Subject Code</th>
      <th>Subject Name</th>
      <th>Ratings</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% if @subjects.empty? %>
      <tr>
        <td align="center" colspan="3">No Subjects Available.</td>
      </tr>
    <% else %>
      <% @subjects.each do |subject| %>
        <tr>
          <td align="center"><%= subject.code %></td>
          <td><%= subject.name %></td>
          <td align="center"><%= starred_rating(subject.ratings) %></td>
          <td align="center">
            <%= link_to subject, title: 'Show' do %>
              <%= fa_icon 'eye' %>
            <% end %> &nbsp;
            <%= link_to edit_subject_path(subject), title: 'Edit' do %>
              <%= fa_icon 'edit' %>
            <% end %> &nbsp;
            <%= link_to subject, method: :delete, data: { confirm: 'Are you sure?' }, title: 'Delete' do %>
              <%= fa_icon 'trash' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<% unless params[:professor_id] %>
  <%= link_to new_subject_path do %>
    <%= fa_icon 'plus' %> New Subject
  <% end %>
<% end %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Subject Details</h1>

<h1><%= starred_rating(@subject.ratings, '2x') %></h1>

<table cellpadding="25">
	<tr>
		<td align="right">Code:</td>
		<td><%= @subject.code %></td>
	</tr>

	<tr>
		<td align="right">Name:</td>
		<td><%= @subject.name %></td>
	</tr>

	<tr>
		<td align="right">Classes:</td>
		<td><%= link_to "View #{pluralize(@subject.class_schedules.size, 'Class')}", polymorphic_path([@subject, ClassSchedule]) %></td>
	</tr>

	<tr>
		<td align="right">Instructors:</td>
		<td><%= link_to "View #{pluralize(@subject.professors.distinct.size, 'Instructor')}", polymorphic_path([@subject, Professor]) %></td>
	</tr>

	<tr>
		<td align="right">Reviews:</td>
		<td><%= link_to "View #{pluralize(@subject.reviews.size, 'Review')}", polymorphic_path([@subject, Review]) %></td>
	</tr>
</table>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>